# Generated by Django 3.2.9 on 2021-12-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_activity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(default='activities/activity_default_placeholder.png', upload_to='activities', verbose_name='Activities'),
        ),
    ]
