# Generated by Django 3.2.9 on 2021-12-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_alter_activity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(default='Augsburg', max_length=300),
        ),
    ]
