# Generated by Django 3.2.9 on 2022-01-14 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_activity_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='enddate',
            field=models.DateField(default=datetime.date(2022, 1, 14), null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='startdate',
            field=models.DateField(default=datetime.date(2022, 1, 14), null=True),
        ),
    ]
