# Generated by Django 3.2.9 on 2022-01-14 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_auto_20220114_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='enddate',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='startdate',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
