# Generated by Django 3.2.9 on 2022-01-14 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_auto_20220114_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='startdate',
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
