# Generated by Django 3.2.9 on 2021-12-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatars/avatar_default_placeholder.png', upload_to='avatars', verbose_name='Avatar'),
        ),
    ]
